# Generated by Django 2.2.7 on 2020-06-19 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('deluxe_cottage', 'deluxe_cottage'), ('honeymoon_cottage', 'honeymoon_cottage'), ('double_bed', 'double_bed'), ('single_bed', 'single_bed')], max_length=50)),
                ('room_rate', models.CharField(max_length=50)),
                ('room_connectiong', models.BooleanField(default=False)),
                ('floor_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_describtion', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=50)),
                ('activity_cost', models.CharField(max_length=50)),
                ('kind_of_activity', models.CharField(choices=[('indoor', 'indoor'), ('outdoor', 'outdoor')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_coder', models.IntegerField(max_length=50, null=True)),
                ('bussiness_name', models.CharField(max_length=255, null=True)),
                ('contact_person_detail', models.CharField(max_length=255, null=True)),
                ('supplier_contact', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('field_of_expertise', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('work_schedule', models.CharField(max_length=255)),
                ('type_supervisor', models.CharField(choices=[('masseuse', 'masseuse'), ('outdoor_instructor', 'outdoor_instructor'), ('swim_instructor', 'swim_instructor')], max_length=50)),
                ('data_supervisor', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='core.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('start_trip', models.DateTimeField()),
                ('end_trip', models.DateTimeField()),
                ('no_of_guest', models.IntegerField()),
                ('no_of_room', models.CharField(max_length=50)),
                ('activity_discount', models.IntegerField()),
                ('trip_discount', models.IntegerField()),
                ('total_price_trip', models.IntegerField()),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_accommodation', to='core.Accommodation')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_activity', to='core.Activity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_info', models.TextField(null=True)),
                ('equip_count', models.IntegerField(null=True)),
                ('inspection_date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_activity', to='core.Activity')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.Supplier')),
            ],
        ),
    ]
