# Generated by Django 2.2.7 on 2020-06-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='bill_coder',
            field=models.IntegerField(null=True),
        ),
    ]
