# Generated by Django 2.2.7 on 2020-06-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200619_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='suplier',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price_trip',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='room_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='activity_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='trip_discount',
            field=models.IntegerField(default=0),
        ),
    ]
