# Generated by Django 2.2.7 on 2020-06-23 10:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200620_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='floor_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inspection_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.Supplier'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='activity_discount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='no_of_room',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='trip_discount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bill_coder',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bussiness_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person_detail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_contact',
            field=models.CharField(max_length=255),
        ),
    ]
