# Generated by Django 2.2.7 on 2020-06-23 10:29

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200623_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='activity_discount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='trip_discount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
    ]
