# Generated by Django 2.2.7 on 2020-06-23 11:06

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200623_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='activity_discount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='trip_discount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
    ]
