# Generated by Django 2.2.7 on 2020-06-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200623_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='no_of_room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
