# Generated by Django 2.2.7 on 2020-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200623_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='activity_discount',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='activity_discount_currency',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='activity',
        ),
        migrations.AddField(
            model_name='reservation',
            name='activity',
            field=models.ManyToManyField(related_name='reservation_activity', to='core.Activity'),
        ),
    ]
