# Generated by Django 2.2.7 on 2020-06-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200623_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='activity_discount',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='activity_discount_currency',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='trip_discount',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='trip_discount_currency',
        ),
    ]
