# Generated by Django 2.2.7 on 2020-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200627_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='trip_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
