# Generated by Django 2.2.7 on 2020-07-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reservation_trip_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='trip_discount',
            field=models.FloatField(default=0),
        ),
    ]
