# Generated by Django 2.2.7 on 2020-06-27 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postcode', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(max_length=50)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('Contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('Marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('Anniversary', models.DateField(blank=True, null=True)),
                ('Blood_pressure', models.BooleanField(default=False)),
                ('Heart_condition', models.BooleanField(default=False)),
                ('Photophobia', models.BooleanField(default=False)),
                ('Acrophobia', models.BooleanField(default=False)),
                ('Address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
